# configuration data
bots:
#    fuchsia: "plugins/ChatCitizen/bots/fuchsia"
#    default: "plugins/ChatCitizen/bots/default"
#    soldier: "plugins/ChatCitizen/bots/soldier"
#    poet: "plugins/ChatCitizen/bots/poet"
#    shop: "plugins/ChatCitizen/bots/shop"
#    pub: "plugins/ChatCitizen/bots/pub"

    root: "plugins/ChatCitizen/bots/root"
    serviceprovider: "plugins/ChatCitizen/bots/serviceprovider"

    default: "plugins/ChatCitizen/bots/root"
    shop: "plugins/ChatCitizen/bots/shop"
    shop2: "plugins/ChatCitizen/bots/shop2"
    fuchsia: "plugins/ChatCitizen/bots/root"
    soldier: "plugins/ChatCitizen/bots/soldier"
    bookshop: "plugins/ChatCitizen/bots/bookshop"
    gemshop: "plugins/ChatCitizen/bots/gemshop"
    pub: "plugins/ChatCitizen/bots/pub"
