# configuration data
bots:
#    fuchsia: "plugins/ChatCitizen/bots/fuchsia"
#    default: "plugins/ChatCitizen/bots/default"
#    soldier: "plugins/ChatCitizen/bots/soldier"
#    poet: "plugins/ChatCitizen/bots/poet"
#    shop: "plugins/ChatCitizen/bots/shop"
#    pub: "plugins/ChatCitizen/bots/pub"

    root: "plugins/ChatCitizen/bots/root"
    pub: "plugins/ChatCitizen/bots/root"
    poet: "plugins/ChatCitizen/bots/root"
    shop: "plugins/ChatCitizen/bots/root"
    fuchsia: "plugins/ChatCitizen/bots/root"
    soldier: "plugins/ChatCitizen/bots/soldier"
