name: ChatCitizen
main: org.pale.chatcitizen2.Plugin
version: 2.0
api-version: 1.13
depend: [Citizens]
commands:
  chatcitizen:
    description: ChatCitizen configuration command
    aliases: [ccz]
    usage: /chatcitizen
    permission: chatcitizen
